### ISSUE TITLE
Unable to get releases for dbslow

### ISSUE THREAD

**Issue by tanc** [tyler36/ddev-dbslow#10]
Hi, was hoping to test this out but I'm getting this error when running `ddev add-on get tyler36/dbslow`:

```
Unable to get releases for dbslow: GET https://api.github.com/repos/tyler36/dbslow/releases?per_page=100: 404 Not Found []
resp.Rate=github.Rate{Limit:60, Remaining:48, Reset:github.Timestamp{2024-10-30 09:14:26 +0100 CET}}
```

**Comment by tyler36** [comment]
Hi @tanc 

Thank you for the feedback.

Looks like there was a regression in the recent waves of add-on updates. 
Use `ddev add-on get tyler36/ddev-dbslow` which should work. 

#11 addresses the issue.

**Comment by tanc** [comment]
Thanks, that works nicely
